# Staging Environment

# Database
spring.datasource.host=${APPLICATION_DATABASE_HOST}
spring.datasource.port=${APPLICATION_DATABASE_PORT}
spring.datasource.name=${APPLICATION_DATABASE_NAME}
spring.datasource.username=${APPLICATION_DATABASE_USERNAME}
spring.datasource.password=${APPLICATION_DATABASE_PASSWORD}

# LLM
gemini.api-key=${GEMINI-API-KEY}